/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.prova.view;

import br.com.prova.dao.FonteDados;
import br.com.prova.dao.FuncionarioDAO;
import br.com.prova.dao.OpcoesSemanaDAO;
import br.com.prova.dao.PedidoDAO;
import br.com.prova.modelo.Funcionario;
import br.com.prova.modelo.OpcoesSemana;
import br.com.prova.modelo.Pedido;
import javax.persistence.EntityManager;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author kelvi
 */
public class FramePedido extends javax.swing.JInternalFrame {
    private EntityManager em1 = FonteDados.createEntityManager();
    private FuncionarioDAO fdao = new FuncionarioDAO(em1);
    private Funcionario f = new Funcionario();
    
    private EntityManager em2 = FonteDados.createEntityManager();
    private OpcoesSemanaDAO opsdao = new OpcoesSemanaDAO(em2);
    private OpcoesSemana ops = new OpcoesSemana();
    
    private EntityManager em3 = FonteDados.createEntityManager();
    private PedidoDAO pddao = new PedidoDAO(em3);
    private Pedido pd = new Pedido();

    /**
     * Creates new form FrameOpcoesFuncionario
     */
    public FramePedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFuncionario = new javax.swing.JLabel();
        txtFuncionario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        lblFuncionario1 = new javax.swing.JLabel();
        lblOpcao4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        lblOpcao5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        lblOpcao6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblOpcao7 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        lblOpcao8 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();

        setTitle("Cadastro das Opções de Funcionário");

        lblFuncionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFuncionario.setText("Funcionário:");

        txtFuncionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "31/12", "07/01", "14/01", "21/01", "28/01", "04/02", "11/02", "18/02", "25/02", "04/03", "11/03", "18/03", "25/03", "01/04", "08/04", "15/04", "22/04", "29/04", "06/05", "13/05", "20/05", "27/05", "03/06", "10/06", "17/06", "24/06" }));

        lblFuncionario1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFuncionario1.setText("Dia de Início da Semana:");

        lblOpcao4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcao4.setText("Opção Dia 1:");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblOpcao5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcao5.setText("Opção Dia 2:");

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        lblOpcao6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcao6.setText("Opção Dia 3:");

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Cadastrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lblOpcao7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcao7.setText("Opção Dia 4:");

        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblOpcao8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcao8.setText("Opção Dia 5:");

        jComboBox6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOpcao5)
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblOpcao8)
                                        .addGap(100, 100, 100))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblOpcao7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOpcao6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblOpcao4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblFuncionario1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblFuncionario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionario)
                    .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionario1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOpcao4)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOpcao5)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOpcao7)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOpcao8)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpcao6)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pd.setItemSegunda(jComboBox2.getSelectedItem()+"");
        pd.setItemTerca(jComboBox3.getSelectedItem()+"");
        pd.setItemQuarta(jComboBox4.getSelectedItem()+"");
        pd.setItemQuinta(jComboBox5.getSelectedItem()+"");
        pd.setItemSexta(jComboBox6.getSelectedItem()+"");
        pd.setFunc(f);
        pd.setOpcoes(ops);
        pddao.create(pd);
        JOptionPane.showMessageDialog(this, "Opções do Funcionário Cadastradas com Sucesso!!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        f = fdao.find(txtFuncionario.getText());
        if (f != null){
            JOptionPane.showMessageDialog(this, "Funcionário encontrado");
        }else{
            JOptionPane.showMessageDialog(this, "Funcionário não encontrado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ops = opsdao.find(jComboBox1.getSelectedItem()+"");
        if(ops != null){
            Object[] itensSegunda = {ops.getItemSegunda1(), ops.getItemSegunda2(), ops.getItemSegunda3()};
            jComboBox2.addItem(itensSegunda[0]);
            jComboBox2.addItem(itensSegunda[1]);
            jComboBox2.addItem(itensSegunda[2]);
            
            Object[] itensTerca = {ops.getItemTerca1(), ops.getItemTerca2(), ops.getItemTerca3()};
            jComboBox3.addItem(itensTerca[0]);
            jComboBox3.addItem(itensTerca[1]);
            jComboBox3.addItem(itensTerca[2]);
            
            Object[] itensQuarta = {ops.getItemQuarta1(), ops.getItemQuarta2(), ops.getItemQuarta3()};
            jComboBox4.addItem(itensQuarta[0]);
            jComboBox4.addItem(itensQuarta[1]);
            jComboBox4.addItem(itensQuarta[2]);
            
            Object[] itensQuinta = {ops.getItemQuinta1(), ops.getItemQuinta2(), ops.getItemQuinta3()};
            jComboBox5.addItem(itensQuinta[0]);
            jComboBox5.addItem(itensQuarta[1]);
            jComboBox5.addItem(itensQuarta[2]);
            
            Object[] itensSexta = {ops.getItemSexta1(), ops.getItemSexta2(), ops.getItemSexta3()};
            jComboBox6.addItem(itensSexta[0]);
            jComboBox6.addItem(itensSexta[1]);
            jComboBox6.addItem(itensSexta[2]);
                        
            JOptionPane.showMessageDialog(this, "Opções da semana encontradas");
        }else{
            JOptionPane.showMessageDialog(this, "Opções da semana não encontradas");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblFuncionario1;
    private javax.swing.JLabel lblOpcao4;
    private javax.swing.JLabel lblOpcao5;
    private javax.swing.JLabel lblOpcao6;
    private javax.swing.JLabel lblOpcao7;
    private javax.swing.JLabel lblOpcao8;
    private javax.swing.JTextField txtFuncionario;
    // End of variables declaration//GEN-END:variables
}
