/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.prova.view;

import br.com.prova.dao.FonteDados;
import br.com.prova.dao.OpcoesSemanaDAO;
import br.com.prova.modelo.OpcoesSemana;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author kelvi
 */
public class FrameOpcoesSemana extends javax.swing.JInternalFrame {

    private EntityManager em = FonteDados.createEntityManager();
    private OpcoesSemanaDAO opsdao = new OpcoesSemanaDAO(em);
    private OpcoesSemana ops = new OpcoesSemana();
    
    private String itemSegunda1, itemSegunda2, itemSegunda3, 
           itemTerca1, itemTerca2, itemTerca3,
           itemQuarta1, itemQuarta2, itemQuarta3,
           itemQuinta1, itemQuinta2, itemQuinta3,
           itemSexta1, itemSexta2, itemSexta3;
    
    /**
     * Creates new form FrameOpcoesSemana
     */
    public FrameOpcoesSemana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDia = new javax.swing.JLabel();
        cbxDia = new javax.swing.JComboBox();
        lblOpcao1 = new javax.swing.JLabel();
        txtOpcao1 = new javax.swing.JTextField();
        lblOpcao2 = new javax.swing.JLabel();
        lblOpcao3 = new javax.swing.JLabel();
        txtOpcao3 = new javax.swing.JTextField();
        txtOpcao2 = new javax.swing.JTextField();
        lblDataInicio = new javax.swing.JLabel();
        txtDataInicio = new javax.swing.JTextField();
        lblDataFim = new javax.swing.JLabel();
        txtDataFim = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setTitle("Cadastro das Opções da Semana");

        lblDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDia.setText("Dia da Semana:");

        cbxDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Segunda-Feira", "Terça-Feira", "Quarta-Feira", "Quinta-Feira", "Sexta-Feira" }));

        lblOpcao1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcao1.setText("Opção 1:");

        txtOpcao1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblOpcao2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcao2.setText("Opção 2:");

        lblOpcao3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcao3.setText("Opção 3:");

        txtOpcao3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtOpcao2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblDataInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataInicio.setText("Data de Início:");

        txtDataInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataInicioActionPerformed(evt);
            }
        });

        lblDataFim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataFim.setText("Data de Término:");

        txtDataFim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cadastrar Opções do Dia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Concluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOpcao3)
                        .addGap(18, 18, 18)
                        .addComponent(txtOpcao3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOpcao2)
                        .addGap(18, 18, 18)
                        .addComponent(txtOpcao2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOpcao1)
                        .addGap(18, 18, 18)
                        .addComponent(txtOpcao1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDataInicio)
                    .addComponent(lblDataFim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDataFim)
                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDia)
                    .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOpcao1)
                            .addComponent(txtOpcao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOpcao2)
                            .addComponent(txtOpcao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOpcao3)
                            .addComponent(txtOpcao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDataInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(lblDataFim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(cbxDia.getSelectedItem()=="Segunda-Feira"){
            itemSegunda1 = txtOpcao1.getText();
            itemSegunda2 = txtOpcao2.getText();
            itemSegunda3 = txtOpcao3.getText();
        }
        if(cbxDia.getSelectedItem()=="Terça-Feira"){
            itemTerca1 = txtOpcao1.getText();
            itemTerca2 = txtOpcao2.getText();
            itemTerca3 = txtOpcao3.getText();
        }
        if(cbxDia.getSelectedItem()=="Quarta-Feira"){
            itemQuarta1 = txtOpcao1.getText();
            itemQuarta2 = txtOpcao2.getText();
            itemQuarta3 = txtOpcao3.getText();
        }
        if(cbxDia.getSelectedItem()=="Quinta-Feira"){
            itemQuinta1 = txtOpcao1.getText();
            itemQuinta2 = txtOpcao2.getText();
            itemQuinta3 = txtOpcao3.getText();
        }
        if(cbxDia.getSelectedItem()=="Sexta-Feira"){
            itemSexta1 = txtOpcao1.getText();
            itemSexta2 = txtOpcao2.getText();
            itemSexta3 = txtOpcao3.getText();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ops.setDataInicio(txtDataInicio.getText());
        ops.setDataTermino(txtDataFim.getText());
        ops.setItemSegunda1(itemSegunda1);
        ops.setItemSegunda2(itemSegunda2);
        ops.setItemSegunda3(itemSegunda3);
        ops.setItemTerca1(itemTerca1);
        ops.setItemTerca2(itemTerca2);
        ops.setItemTerca3(itemTerca3);
        ops.setItemQuarta1(itemQuarta1);
        ops.setItemQuarta2(itemQuarta2);
        ops.setItemQuarta3(itemQuarta3);
        ops.setItemQuinta1(itemQuinta1);
        ops.setItemQuinta2(itemQuinta2);
        ops.setItemQuinta3(itemQuinta3);
        ops.setItemSexta1(itemSexta1);
        ops.setItemSexta2(itemSexta2);
        ops.setItemSexta3(itemSexta3);
        opsdao.create(ops);
        JOptionPane.showMessageDialog(this, "Opções da Semana Cadastrado com Sucesso!!!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxDia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lblDataFim;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblOpcao1;
    private javax.swing.JLabel lblOpcao2;
    private javax.swing.JLabel lblOpcao3;
    private javax.swing.JTextField txtDataFim;
    private javax.swing.JTextField txtDataInicio;
    private javax.swing.JTextField txtOpcao1;
    private javax.swing.JTextField txtOpcao2;
    private javax.swing.JTextField txtOpcao3;
    // End of variables declaration//GEN-END:variables
}
